baseurl = "http://yourSiteHere"
languageCode = "en-us"
title = "A Hugo Foundation Template"
[[menu.main]]
    name = "test"
    weight = -110
    identifier = "test item"
[[menu.footer]]
    name = "about this site"
    weight = -110
    identifier = "about"