baseurl = "http://localhost:1313"
languageCode = "en-us"
title = "A Hugo Foundation Starter"
[[menu.footer]]
    name = "about this site"
    weight = -110
    identifier = "about"
 [params]   
    sidebartitle="This is the Sidebar"
[[menu.social]]
    name = "Facebook"
    url = "www.facebook.com"
    weight = 200
    identifier = "facebook"
[[menu.social]]
    name = "Twitter"
    url = "www.twitter.com"
    weight = 200
    identifier = "twitter"    